spring:
  application:
    name: users-msvc

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql8:3306/user_docker?serverTimezone=America/Lima&allowPublicKeyRetrieval=false
    password: 12345
    username: root

    #Jpa-Hibernate
  jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
      hibernate:
        ddl-auto: update
server:
  port: 8001

