spring:
  application:
    name: courses-mcsv

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:postgres14:5432}/${DB_DATABASE:courses-docker}
    password: ${DB_PASSWORD:12345}
    username: ${DB_USERNAME:postgres}

    #Jpa-Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

server:
  port: ${PORT:8002}

micro:
  users:
    url: ${USERS_URL:users-msvc:8001/api/v1/users}
