spring:
  application:
    name: courses-mcsv

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres14:5432/courses-docker
    password: 12345
    username: postgres

    #Jpa-Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

server:
  port: 8002

